# Generated by Django 3.2 on 2024-01-18 13:06

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.validate_username], verbose_name='Никнейм'),
        ),
    ]
