# Generated by Django 3.2 on 2024-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, verbose_name='Код подтверждения'),
        ),
    ]
